wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1709267442.788732
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      - 105
      2:
      - 1
      - 5
      - 53
      - 55
      - 105
      3:
      - 1
      - 23
      4: 3.11.5
      5: 0.16.3
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
